version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBIT_MQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "8082:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    container_name: rabbitmq
    labels:
      NAME: rabbitmq
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitmq-server

  dotnet-consumer:
    image: dotnet-consumer-image
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-server
  dotnet-api:
    image: dotnet-api-image
    build:
      context: ./MessagingApi
      dockerfile: Dockerfile
    ports:
      - "8081:5001"
    depends_on:
      - rabbitmq
      - dotnet-consumer
    networks:
      - rabbitmq-server

networks:
  rabbitmq-server:
    driver: bridge
