version: "3.7"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        environment:
            RABBIT_MQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
        container_name: rabbitmq
        labels:
            NAME: rabbitmq
        volumes:
            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
        networks:
            - rabbitmq-server
    
    dotnet:
        image: dotnet-image
        build:
            context: ./Backend
            dockerfile: Dockerfile
        depends_on:
            - rabbitmq
        networks:
            - rabbitmq-server
        
networks:
    rabbitmq-server:
        driver: bridge            